gt4sd-trainer-hf-pl --model_config_name t5_tiny \
    --tokenizer t5-small \
    --type cgm \
    --lr 1e-3 \
    --lr_decay 0.99 \
    --cache_dir /tmp/dcii_ \
    --batch_size 16 \
    --accumulate_grad_batches 4 \
    --max_length 756 \
    --monitor val_loss \
    --train_file  /Users/arv/Projects/nmr/pistachio/t5/test_file.json \
    --validation_file /Users/arv/Projects/nmr/pistachio/t5/test_file.json \
    --default_root_dir /Users/arv/Projects/nmr/pistachio/t5 \
    --val_check_interval 5  \
    --max_epochs 3 \
    --limit_val_batches 500 \
    --every_n_train_steps 20000 \
    --log_every_n_steps 5000 \
    --save_top_k 1 \
    --mode min \
    --accelerator 'gpu' \
    --devices 1
